### ISSUE TITLE
win-11-virtual-desktop-enhancer 

### ISSUE THREAD

**Issue by franzbu** [mhyllander/gpg-bridge-wsl2-ruby#17]
As reporting issues seems to be deactivated in 'win-11-virtual-desktop-enhancer', I take the liberty of reporting here.

First, thanks a lot for this port to AHK v2. In line 468 of virtual-desktop-enhancer.ahk I need to switch to the function 'WinExist" instead of "WinGetID" to get rid of the error message "Target window not found". Afterwards everything works smoothly on Windows 11 ARM (MS Surface Pro 11).

taskbarSecondaryID := **WinExist**("ahk_class Shell_SecondaryTrayWnd")

**Comment by mhyllander** [comment]
@franzbu Thanks for reporting! (And I've enabled issues 😃.)
